# Generated by Django 3.1 on 2020-08-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('date_of_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
